### ISSUE TITLE
do while

### ISSUE THREAD

**Issue by ghost** [fritzone/obfy#11]
how to obfuscate code with `do while`?
```

	do {
		...
		}
	} while (dwStatus == ERROR_BUFFER_OVERFLOW && i-- > 0);
```

for example

**Comment by fritzone** [comment]
use the REPEAT/AS_LONG_AS as presented in the article:

    REPEAT
        std::cout << a << std::endl;
        ++ V(a);
    AS_LONG_AS( V(a) != N(12) )
