### ISSUE TITLE
Demo project with obfy

### ISSUE THREAD

**Issue by ghost** [fritzone/obfy#12]
I'm use you are framework in 'open-license-manager'.

Demo:
https://github.com/lurumdare/open-license-manager/tree/obfy

Maybe you review code?

**Comment by fritzone** [comment]
Yes, I think that might be possible, but please let me know when your project is ready for release.

**Comment by ghost** [comment]
@fritzone project stable. All tests passed.

**Comment by fritzone** [comment]
Ok, I will try to look at the code some time this week. If I find something I shall get back to you.

**Comment by ghost** [comment]
@fritzone Thanks.

**Comment by fritzone** [comment]
Did some code review. Where can I send the results?

**Comment by ghost** [comment]
@fritzone matthew0haig@gmail.com
