### ISSUE TITLE
Cases: not work

### ISSUE THREAD

**Issue by ghost** [fritzone/obfy#14]
Before
![](https://i.imgur.com/4EYaauO.png)

After
![](https://i.imgur.com/smVBtfr.png)

and it does not work

Error

` 'add_default': identifier not found`

**Comment by fritzone** [comment]
`BREAK` statement should come before `DONE`

**Comment by ghost** [comment]
@fritzone
Not work

![](https://i.imgur.com/YoKUj6Z.png)

**Comment by fritzone** [comment]
It's not `WHEN(DEFAULT)` or OBF_DEFAULT just plain `DEFAULT` :

    CASE (<variable>)
        WHEN(<value>) [OR WHEN(<other_value>)] DO
        ....statements
        ....[BREAK]
        DONE
        [DEFAULT
        ....statements
        DONE]
    ENDCASE

**Comment by ghost** [comment]
@fritzone DEFAULT equal 0 (typedef enum)

**Comment by ghost** [comment]
@fritzone I think cases not work correctly.

Check https://github.com/lurumdare/VM_Crackme/blob/master/VM_CrackMe/vm.cpp#L356 this project. 
retv error again. 

Code 
```
DWORD OldVirtualMachine::GetRegValue(int regs)
{
	OBF_BEGIN
	CASE ((regs))
	WHEN (eax) DO
		RETURN (reg.eax);
		DONE
	WHEN (ecx) DO
		RETURN (reg.ecx);
		DONE
	WHEN (edx) DO
		RETURN (reg.edx);
		DONE
	WHEN (ebx) DO
		RETURN (reg.ebx);
		DONE
	WHEN (ebp) DO
		RETURN (reg.ebp);
		DONE
	WHEN (esp) DO
		RETURN (reg.esp);
		DONE
	WHEN (eip) DO
		RETURN (reg.eip);
		DONE
	DEFAULT
		//бесполезно - надо генерить исключение
		RETURN(false);
	DONE
	ENDCASE
	OBF_END
}
```
