### ISSUE TITLE
unused variable '__crv'

### ISSUE THREAD

**Issue by Macintron** [fritzone/obfy#18]
Compiling with Xcode 11 results in this error (7 times):
```
/obfy/main.cpp:27:5: error: unused variable '__crv' [-Werror,-Wunused-variable]
    OBF_BEGIN
    ^
In file included from /obfy/main.cpp:9:
/obfy/instr.h:816:40: note: expanded from macro 'OBF_BEGIN'
#define OBF_BEGIN try { obf::next_step __crv = obf::next_step::ns_done; std::shared_ptr<obf::base_rvholder> __rvlocal;
                                       ^
/obfy/main.cpp:36:2: error: unused variable '__crv' [-Werror,-Wunused-variable]
        OBF_BEGIN
        ^
```

cmake automatically created the `-Werror` when creating the Xcode project with `cmake -GXcode .`.

Should be easy to fix: insert an 'unused expression' for `__crv`:
`#define OBF_BEGIN try { obf::next_step __crv = obf::next_step::ns_done; std::shared_ptr<obf::base_rvholder> __rvlocal; (void)__crv;`
or
`#define OBF_END (void)__crv; } catch(std::shared_ptr<...`
wherever it makes more sense.

**Comment by fritzone** [comment]
That actually happens only if you have an empty bodied

    OBF_BEGIN
    OBF_END

obfuscation block, but regardless I added a `(void)__crv;` in the `OBF_BEGIN` to not to have this issue creeping up again.

**Comment by Macintron** [comment]
Yep, `FOR`, `WHILE`, `REPEAT` etc. commands use the `__crv`.
This is (was) a perfectionist issue which is for those with highest warning levels enabled.
Anyway, thanks for fixing this to make this project even more perfect.
