### ISSUE TITLE
RETURN and void function

### ISSUE THREAD

**Issue by sgolubev33** [fritzone/obfy#21]
Hello,

how to correctly call OBF RETURN in case of void returning function?

RETURN(void) and RETURN() generating compilation errors.

Regards

**Comment by fritzone** [comment]
Oh well, this is not implemented yet... Just use plain "return;" for now, I might implement this in case I will have time in coming weeks.

**Comment by sgolubev33** [comment]
Thank you in advance!

**Comment by sgolubev33** [comment]
Unfortunatelly after replace RETURN to return; receiveing compilation error in the following construction:
IF( dt <= 0 )
        return;
ENDIF

it seems, using of simle return does not allowed here
