### ISSUE TITLE
Virtual destructors and memory leaks

### ISSUE THREAD

**Issue by hebaishi** [fritzone/obfy#22]
Hello. I am seeing memory leaks reported by GCC's LeakSanitizer.
The issue is missing virtual destructors in `next_step_functor_base`, `bool_functor_base`, `any_functor_base` and `case_wrapper_base`, causing a `new-delete-mismatch` error to be reported by the sanitizer. I'm happy to open a PR to fix the issue - or you could do it if you prefer. Please let me know how you would like me to go about it. I can either:
* Fork the repository, make the change in my fork, and make a PR.
* If you added me as a contributor to this repo, I can make a PR here directly.

**Comment by fritzone** [comment]
Thanks for reporting this issue. You were sent an invitation, feel free to fix the raised issue or other ones you might find.
