### ISSUE TITLE
Error with int64 num obfuscation

### ISSUE THREAD

**Issue by Bk8** [fritzone/obfy#3]
When I obfuscate an int64 I get a weird number, I'm compiling in Xcode with Clang.

int64  bigNumber;
V(bigNumber) = N(1537232811123);

The assigned number to the variable is -365480845.

**Comment by fritzone** [comment]
Hi,

Thanks for reporting this issue! The problem was that by default a C++ enum is an int on 32 bits, and the requested number did not fit in.

Problem fixed, please pull and test!

**Comment by afwn90cj93201nixr2e1re** [comment]
Damn, it's not tiny library at all.
