### ISSUE TITLE
V macro doesn't work correctly

### ISSUE THREAD

**Issue by spectrumnlt** [fritzone/obfy#4]
I faced a problem that whenever I try to use macro V to obfuscate variables it shows me an error in the macro definition :
![image](https://user-images.githubusercontent.com/44167596/49174324-11bb6c00-f357-11e8-8147-176b6d34fea7.png)

So it compiles correctly only if you make this field public. On the other hand comment there contains this:
![image](https://user-images.githubusercontent.com/44167596/49174406-4fb89000-f357-11e8-902b-4a81eb8922af.png)

Are there any options to fix it without editing the class with that comment?

**Comment by spectrumnlt** [comment]
Compilier: Visual Studio 2017

**Comment by spectrumnlt** [comment]
Even if you make that field public it won't compile too
![image](https://user-images.githubusercontent.com/44167596/49174894-67444880-f358-11e8-8d83-bbfb86a59b63.png)

**Comment by fritzone** [comment]
Hi,

1. Could you please create a small, self contained program which exposes the same behaviour and post it here? I have created the following test case for that line of code you presented:

```cpp
int simple_variable_wrapper_min_eq()
{
	int n = 64;
	OBF_BEGIN
		V(n) -= n << N(2);
	OBF_END
	return n;
}
```
which compiles without problems using gcc (7.3.0) and runs too. 

2. Did you try a different compiler?

**Comment by spectrumnlt** [comment]
1. Very strange. Visual studio highlights it as an error:
![image](https://user-images.githubusercontent.com/44167596/49211540-d9f10a80-f3d0-11e8-8ae6-ef5bb35f551d.png)
But anyway it compiles and runs successfully
https://pastebin.com/V98Z9han
2. No, I didn''t

**Comment by fritzone** [comment]
Yep, the code behind those macros are pretty complex, so there is a slight chance that some IDE's will not be able to properly parse, interpret and evaluate them thus flagging as error, however the compiler is the one we should trust. I'll close the issue now.
