### ISSUE TITLE
add FOREACH

### ISSUE THREAD

**Issue by ghost** [fritzone/obfy#9]
maybe add?

for example I have code 
`for (auto it = licenses.begin(); it != licenses.end(); it++) {`

how to add `obfy` to this?

**Comment by fritzone** [comment]
Adding FOREACH sounds like a great idea! Thanks, I will consider implementing it.

Meanwhile you could use an index based loop as a workaround?

**Comment by ghost** [comment]
@fritzone I think about it. Maybe ur make example?
